title: Thomas Finley
description: >-
  The personal website of Thomas Finley, a software developer and machine
  learning expert.
baseurl: ""
domain: "tomfinley.github.io"
url: "https://tomfinley.github.io"
twitter_username: ThomasWFinley
github_username:  TomFinley
show_excerpts: true
markdown: kramdown
remote_theme: jekyll/minima@7a326eb

author:
  name: "Thomas Finley"
  email: tfinley@gmail.com

header_pages:
  - publications.md
  - academic-notes.md
  - llm/index.md
  - blog.md

permalink_old: /:categories/:year/:title:output_ext
permalink: /:categories/:year/:title

# Build settings
theme: minima
plugins:
  #- jekyll-feed
  - jekyll-remote-theme

exclude:
  - README.md
  - test.sh
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

minima:
  skin: tom
  social_links:
    github:  TomFinley
    gitlab:
     - username: TFinley
       instance: gitlab.com
    facebook: thomas.finley.921
    linkedin: thomas-finley-a39b203
